/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.philng.telemetrydisplay;

import com.philng.telemetrydisplay.Serial.SerialReader;
import com.philng.telemetrydisplay.controller.Controller;
import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.*;

/**
 * Main UI
 * @author phil
 */
public class GUI extends javax.swing.JFrame {
    public Controller controller;
    public GraphDisplay graphDisplay;
    Thread loaderThread;

    /**
     * Creates new form GUI
     */
    public GUI(Controller controller) {
        initComponents();
        initCustom();
        this.controller = controller;
        this.graphDisplay = new GraphDisplay();
        
        dataPanel.setLayout( new BorderLayout() );
        dataPanel.add(this.graphDisplay, BorderLayout.CENTER);
        this.pack();
    }
    
    public GUI(){
        initComponents();
        initCustom();
    }
    
    public void initCustom(){
        Connect connectListener = new Connect();
        connectSerialButton.addActionListener(connectListener);
        ResetAction resetListener = new ResetAction();
        resetButton.addActionListener(resetListener);
        refreshPortsButtonMouseClicked(null);
        getPreferredSerialPort();
    }

    public void getPreferredSerialPort(){
        for(int i = 0; i<jComboBox3.getModel().getSize();i++){
            if( ((String) jComboBox3.getModel().getElementAt(i)).contains("tty.RNBT")){
                jComboBox3.setSelectedIndex(i);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jComboBox3 = new javax.swing.JComboBox();
        connectSerialButton = new javax.swing.JButton();
        refreshPortsButton = new javax.swing.JButton();
        dataPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Racing Telemetry Viewer");
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        connectSerialButton.setText("Connect");
        connectSerialButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connectSerialButtonMouseClicked(evt);
            }
        });
        connectSerialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectSerialButtonActionPerformed(evt);
            }
        });

        refreshPortsButton.setText("Refresh Ports");
        refreshPortsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshPortsButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        resetButton.setText("Reset Data");

        jMenu1.setText("File");

        jMenuItem1.setText("Save Data");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshPortsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectSerialButton)
                .addContainerGap())
            .addComponent(jSeparator1)
            .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectSerialButton)
                    .addComponent(refreshPortsButton)
                    .addComponent(statusLabel)
                    .addComponent(resetButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectSerialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectSerialButtonActionPerformed

    }//GEN-LAST:event_connectSerialButtonActionPerformed

    private void connectSerialButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectSerialButtonMouseClicked
    }//GEN-LAST:event_connectSerialButtonMouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void refreshPortsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshPortsButtonMouseClicked
        jComboBox3.removeAllItems();
        ArrayList<String> ports = SerialReader.getInstance().getAvailablePorts();
        for(String s : ports){
            jComboBox3.addItem(s);
        }
    }//GEN-LAST:event_refreshPortsButtonMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public static void main(String[] args) {

        EventQueue.invokeLater(new Runnable() {
        
            @Override
            public void run() {
                try {
                    System.setProperty("apple.laf.useScreenMenuBar", "true");
                    System.setProperty("com.apple.mrj.application.apple.menu.about.name", "Racing Telemetry");
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch(Exception e){

                }


                final Controller controller = new Controller();
                GUI ex = new GUI(controller);
                ex.setVisible(true);
                controller.setUI(ex);

                // Disconnect if connected while exiting application
                Runtime.getRuntime().addShutdownHook(new Thread()
                {
                    @Override
                    public void run()
                    {
                        System.out.println("Application Exiting");
                        controller.disconnectPort();
                    }
                });

            }
        });
    }
    class ResetAction extends AbstractAction implements Runnable {
         @Override
        public void actionPerformed (ActionEvent e) {
            if (loaderThread != null)
                    return;
            loaderThread = new Thread ((Runnable) this);
            loaderThread.start();

        }
        public void run(){
            controller.clearData();
        }
        
    }
    class Connect extends AbstractAction implements Runnable {

        @Override
        public void actionPerformed (ActionEvent e) {
            if (loaderThread != null)
                    return;
            loaderThread = new Thread ((Runnable) this);
            loaderThread.start();

        }
        public void run(){
            if(connectSerialButton.getText().equals("Connect")){
                controller.connectPort(jComboBox3.getSelectedItem().toString());
            } else {
                controller.disconnectPort();
            }
            loaderThread = null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton connectSerialButton;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton refreshPortsButton;
    private javax.swing.JButton resetButton;
    public javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}

